name: CreativeGuard
main: CreativeGuard.Main
version: 1.0
api-version: 1.13
permissions:
  creativeguard.admin:
    description: Allows the normal use of gamemode without restrictions
    default: op
  creativeguard.interact.<ITEM_NAME>:
    description: "Allows the use of objects that are not blocks such as: WATER_BUCKET,LAVA_BUCKET,EXPERIENCE_BOTTLE etc."
    default: false
  creativeguard.place.<ITEM_NAME>:
    description: "Allows placement of prohibited items from config"
    default: false
  creativeguard.build.iron_golem:
    description: Allows users in creative mode to build iron golems
    default: op
  creativeguard.build.snow_golem:
    description: Allows users in creative mode to build iron golems
    default: op
  creativeguard.arrowinsruments:
    description: Allows users in creative mode to use arrow instruments like bow and crossbow
    default: op
  creativeguard.droppotion:
    description: Allow users in creative mode to drop potions
    default: op
  creativeguard.gamemode.getdropsentity:
    description: Allow users in creative mode to get drop from entity (Config default is disable)
    default: op
  creativeguard.frame.item:
    description: Allow users in creative mode to set items in frame
    default: op
  creativeguard.spawnegg.<ITEM_NAME>:
    description: Allow users in creative mode to spawn entity from egg
    default: op
  creativeguard.place_egg_in_spawner:
    description: Allow users in creative mode to place entity egg in spawner
    default: op
  creativeguard.creative.attack:
    description: Allow users in creative mode to attack another entity or players
    default: op
  creativeguard.dropitem:
    description: "Allow users in creative mode to drop items"
    default: op
  creativeguard.open.<INVENTORY_NAME>:
    description: Allow users in creative mode to open inventories like chest, ender_chest and etc.
    default: false
  creativeguard.disable.changeinventory:
    description: This permission disable change gamemode inventories
    default: op
  creativeguard.place_custom_items:
    description: This permission allow to place custom items
    default: op
  creativeguard.use.buckets:
    description: This permission allow to use buckets and buckets with animals
    default: op
  creativeguard.use.armor_stand:
    description: This permission allow creative mode to use armor_stand
    default: op
  creativeguard.use.lead:
    description: This permission allow to creative mode use lead
    default: op
  creativeguard.use.shear_entity:
    description: This permission allow to creative mode use shear on entity
    default: op
  creativeguard.useblock.<BLOCK_NAME>:
    description: This permission allow to creative mode to use blocks, like composter and other
    default: op
  creativeguard.eat:
    description: This permission allow to creative mode eat
    default: op
  creativeguard.pickup:
    description: This permission allow to creative mode get droped items
    default: op
  creativeguard.prevent_entity.<ENTITY_NAME>:
    description: This permission prohibits creative from interacting with the entity
    default: op
  creativeguard.place_falling.<BLOCK_NAME>:
    description: This permission allow to creative mode to place falling blocks like gravel and sand
    default: op
  creativeguard.break.<BLOCK_NAME>:
    description: This permission allow to creative mode to break forbiden block
    default: op
  creativeguard.throw.trident:
  	description: This permission allow to creative mode to threw trident
  	default: op